# -*- coding: utf-8 -*-
"""Tuning V5 Penelitian Cabai LastV

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y2YtYfRXOFQVcuhtCLAL8WfpYWvR0w3k
"""

!pip install arch

import pandas as pd
import numpy as np

# 1. Memuat Dataset
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/PaperCabai/harga_cabai_tradisional_full.csv')

# 2. Identifikasi kolom dasar secara benar (tambahkan 'provinsi')
# Pastikan 'provinsi' tidak ikut masuk ke dalam list kolom_tanggal
kolom_dasar = ['no', 'name', 'level', 'provinsi']
kolom_tanggal = [col for col in df.columns if col not in kolom_dasar]

# 3. Mengubah format Wide menjadi Long (Melt)
df_long = pd.melt(
    df,
    id_vars=kolom_dasar,
    value_vars=kolom_tanggal,
    var_name='Tanggal',
    value_name='Harga'
)

# 4. Membersihkan kolom Harga
# Ubah ke string -> Hapus koma -> Ganti '-' atau spasi kosong murni jadi NaN -> Ubah ke float
df_long['Harga'] = df_long['Harga'].astype(str).str.replace(',', '', regex=False)
df_long['Harga'] = df_long['Harga'].str.strip()
df_long['Harga'] = df_long['Harga'].replace({'-': np.nan, '': np.nan, 'nan': np.nan})
df_long['Harga'] = pd.to_numeric(df_long['Harga'], errors='coerce')

# 5. Mengubah tipe data Tanggal menjadi Datetime dan Mengurutkan Data
df_long['Tanggal'] = pd.to_datetime(df_long['Tanggal'], format='%d/%m/%Y')
# Urutkan berdasarkan provinsi, komoditas (name), dan kronologi tanggal
df_long = df_long.sort_values(by=['provinsi', 'name', 'Tanggal']).reset_index(drop=True)

# 6. Menangani NaN (Missing Values) dengan ffill lalu bfill
# Gunakan groupby ['provinsi', 'name'] agar harga Cabai Merah & Rawit tidak saling menimpa
df_long['Harga'] = df_long.groupby(['provinsi', 'name'])['Harga'].transform(lambda x: x.ffill().bfill())

# 7. Menghitung Return Harian
# pct_change() = (Harga hari ini - Harga kemarin) / Harga kemarin
df_long['Return'] = df_long.groupby(['provinsi', 'name'])['Harga'].pct_change()

# 8. Menghapus nilai Return yang NaN (Hari pertama tiap komoditas per provinsi)
df_bersih = df_long.dropna(subset=['Return']).reset_index(drop=True)

# Menyimpan hasil ke CSV
df_bersih.to_csv('dataset_garch_cabai_bersih.csv', index=False)

# Menampilkan hasil
print(f"Total baris data: {len(df_bersih)}")
print(f"Total provinsi unik: {df_bersih['provinsi'].nunique()}")
print("\nCuplikan 5 baris pertama:")
print(df_bersih.head())

import pandas as pd
from arch import arch_model
import warnings

# Mengabaikan warning konvergensi agar output terminal tetap bersih
warnings.filterwarnings('ignore')

# 1. Memuat dataset yang sudah bersih
df = pd.read_csv('dataset_garch_cabai_bersih.csv')

# 2. Mengalikan Return dengan 100
df['Return_100'] = df['Return'] * 100

hasil_volatilitas = []

provinsi_unik = df['provinsi'].unique()

print(f"Mulai melatih model GARCH(1,1) untuk {len(provinsi_unik)} Provinsi...")
print("Proses sedang berjalan, mohon tunggu sebentar...\n")

for prov in provinsi_unik:
    df_prov = df[df['provinsi'] == prov]
    volatilitas_komoditas = []

    for komoditas in df_prov['name'].unique():
        returns = df_prov[df_prov['name'] == komoditas]['Return_100'].dropna()

        if len(returns) < 10:
            continue

        try:
            model = arch_model(returns, mean='Constant', vol='GARCH', p=1, q=1)
            res = model.fit(disp='off')
            rata_rata_vol = res.conditional_volatility.mean()
            volatilitas_komoditas.append(rata_rata_vol)
        except Exception as e:
            pass

    if volatilitas_komoditas:
        vol_provinsi = sum(volatilitas_komoditas) / len(volatilitas_komoditas)
        hasil_volatilitas.append({
            'Provinsi': prov,
            'Nilai_Volatilitas': vol_provinsi
        })

print(" Proses fitting GARCH selesai!\n")

# 2. Membuat DataFrame dan menampilkan hasil
if len(hasil_volatilitas) > 0:
    df_hasil = pd.DataFrame(hasil_volatilitas)
    df_hasil = df_hasil.sort_values(by='Nilai_Volatilitas', ascending=False).reset_index(drop=True)

    print(f"Total Provinsi yang berhasil diekstrak volatilitasnya: {len(df_hasil)}")
    print("-" * 50)
    print(df_hasil.to_string())

    df_hasil.to_csv('hasil_volatilitas_garch_provinsi.csv', index=False)
    print("\n Data telah disimpan sebagai 'hasil_volatilitas_garch_provinsi.csv'")
else:
    print(" Gagal: Tidak ada provinsi yang berhasil dimodelkan. Cek kembali isi data 'Return_100'.")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Asumsi: Anda sudah memiliki df_hasil dari tahapan sebelumnya.
# Jika belum, pastikan nama DataFrame Anda sudah disesuaikan.
# df_hasil = pd.read_csv('hasil_volatilitas_garch_provinsi.csv')

# 1. Mengubah format ke array 2D
# Scikit-learn membutuhkan input berukuran (n_samples, n_features)
X = df_hasil['Nilai_Volatilitas'].values.reshape(-1, 1)

# 2. Mencari K optimal (K = 2, 3, 4, 5) menggunakan Silhouette dan Inertia (Elbow)
K_range = [2, 3, 4, 5]
inertia_values = []
silhouette_scores = []

print("=== Evaluasi Jumlah Cluster (K) ===")
best_k = 2
best_score = -1

for k in K_range:
    # random_state=42 agar hasil konsisten setiap kali di-run
    # n_init=10 untuk menghindari warning scikit-learn versi terbaru
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X)

    # Simpan nilai Inertia (untuk Metode Elbow)
    inertia_values.append(kmeans.inertia_)

    # Hitung dan simpan Silhouette Score
    score = silhouette_score(X, kmeans.labels_)
    silhouette_scores.append(score)

    print(f"K = {k} | Inertia = {kmeans.inertia_:.4f} | Silhouette Score = {score:.4f}")

    # Update K terbaik berdasarkan Silhouette Score tertinggi
    if score > best_score:
        best_score = score
        best_k = k

print(f"\nBerdasarkan Silhouette Score tertinggi, K optimal yang dipilih adalah: {best_k}")

# Opsional: Menampilkan grafik Elbow dan Silhouette jika ingin melihat visualnya

fig, ax1 = plt.subplots(figsize=(8, 4))
ax1.plot(K_range, inertia_values, marker='o', color='b', label='Inertia (Elbow)')
ax1.set_xlabel('Jumlah Cluster (K)')
ax1.set_ylabel('Inertia', color='b')

ax2 = ax1.twinx()
ax2.plot(K_range, silhouette_scores, marker='s', color='r', label='Silhouette Score')
ax2.set_ylabel('Silhouette Score', color='r')

plt.title('Metode Elbow & Silhouette Score')
plt.show()

# 3. Menjalankan algoritma K-Means dengan K yang paling optimal
kmeans_optimal = KMeans(n_clusters=best_k, random_state=42, n_init=10)
cluster_labels = kmeans_optimal.fit_predict(X)

# 4. Menambahkan kolom 'Cluster' pada DataFrame awal
df_hasil['Cluster'] = cluster_labels

# 5. Mengurutkan tabel dari volatilitas tertinggi ke terendah
df_final = df_hasil.sort_values(by='Nilai_Volatilitas', ascending=False).reset_index(drop=True)

print("\n=== Hasil Akhir Clustering Provinsi ===")
print(df_final.to_string())

# Opsional: Menyimpan ke CSV baru
df_final.to_csv('provinsi_clustered.csv', index=False)

import matplotlib.pyplot as plt
import pandas as pd
import random
from arch import arch_model

# =====================================================================
# OUTPUT 1: Visualisasi Imbal Hasil (Daily Return) 3 Provinsi Sampel
# =====================================================================
print("=== 1. Menyiapkan Plot Visualisasi Daily Return ===")

# Mengambil sampel berdasarkan urutan indeks di df_final (karena sudah disortir)
prov_tinggi = df_final.iloc[0]['Provinsi']            # Indeks pertama = Tertinggi
prov_rendah = df_final.iloc[-1]['Provinsi']           # Indeks terakhir = Terendah
prov_tengah = df_final.iloc[len(df_final)//2]['Provinsi'] # Indeks di tengah = Median

prov_samples = [prov_tinggi, prov_tengah, prov_rendah]
labels = ['Volatilitas Tertinggi', 'Volatilitas Menengah', 'Volatilitas Terendah']
warna = ['red', 'orange', 'green']

plt.figure(figsize=(14, 7))

for prov, label, color in zip(prov_samples, labels, warna):
    # Mengambil data return untuk provinsi tersebut (mengutamakan 'Cabai Rawit')
    df_plot = df[(df['provinsi'] == prov) & (df['name'] == 'Cabai Rawit')].copy()

    # Jika kebetulan 'Cabai Rawit' kosong, ambil komoditas apa saja yang ada
    if df_plot.empty:
         komoditas_ada = df[df['provinsi'] == prov]['name'].iloc[0]
         df_plot = df[(df['provinsi'] == prov) & (df['name'] == komoditas_ada)].copy()

    # Mengambil nilai return-nya saja sebagai array (agar sumbu X menggunakan urutan hari ke-n)
    nilai_return = df_plot['Return_100'].values

    # Plotting garis
    plt.plot(nilai_return, label=f"{prov} ({label})", color=color, alpha=0.7, linewidth=1.5)

plt.title('Perbandingan Imbal Hasil (Daily Return) Cabai Rawit di 3 Provinsi Sampel', fontsize=14, pad=15)
plt.xlabel('Hari Pengamatan', fontsize=12)
plt.ylabel('Return (%)', fontsize=12)
plt.legend(loc='upper right')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()

# Menampilkan Grafik
plt.show()

# =====================================================================
# OUTPUT 2: Tabel Parameter GARCH(1,1) untuk 5 Provinsi Acak
# =====================================================================
print("\n=== 2. Mengekstrak Parameter GARCH(1,1) untuk 5 Provinsi Sampel ===")

# Mengambil 5 provinsi acak (random_state agar provinsi yang terpilih konsisten tiap run)
random.seed(42)
prov_acak = random.sample(list(df_final['Provinsi']), 5)

hasil_parameter = []

for prov in prov_acak:
    df_prov = df[df['provinsi'] == prov]
    komoditas_pertama = df_prov['name'].unique()[0]
    returns = df_prov[df_prov['name'] == komoditas_pertama]['Return_100'].dropna()

    if len(returns) >= 10:
        model = arch_model(returns, mean='Constant', vol='GARCH', p=1, q=1)
        res = model.fit(disp='off')

        # Mengekstrak nilai estimasi parameter omega, alpha, dan beta
        # Di library arch, nama default-nya adalah 'omega', 'alpha[1]', dan 'beta[1]'
        omega = res.params.get('omega', None)
        alpha = res.params.get('alpha[1]', None)
        beta  = res.params.get('beta[1]', None)

        hasil_parameter.append({
            'Provinsi': prov,
            'Komoditas': komoditas_pertama,
            'Omega': round(omega, 6),
            'Alpha': round(alpha, 6),
            'Beta': round(beta, 6)
        })

# Membuat DataFrame untuk tabel parameter
df_params = pd.DataFrame(hasil_parameter)
print(df_params.to_string(index=False))

# Opsional: Simpan tabel ke Excel/CSV untuk di-copy paste ke Word/Jurnal
# df_params.to_csv('tabel_parameter_garch.csv', index=False)

# OUTPUT 2.1: Ringkasan Mean Conditional Volatility Provinsi Sampel

print("\n=== 2.1. Ringkasan Mean Conditional Volatility ===")

import random
random.seed(42)

# Ambil 5 provinsi secara acak
prov_acak = random.sample(list(df_final['Provinsi'].unique()), 5)

hasil_volatilitas = []

for prov in prov_acak:

    nilai_vol = df_final[
        df_final['Provinsi'] == prov
    ]['Nilai_Volatilitas'].values[0]

    hasil_volatilitas.append({
        'Provinsi': prov,
        'Mean Conditional Volatility': round(nilai_vol, 6)
    })

df_vol = pd.DataFrame(hasil_volatilitas)

print(df_vol.to_string(index=False))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Asumsi df_hasil sudah ada dari tahap sebelumnya.
# Jika belum, load dari csv: df_hasil = pd.read_csv('hasil_volatilitas_garch_provinsi.csv')

# Ambil data volatilitas untuk clustering
X = df_hasil['Nilai_Volatilitas'].values.reshape(-1, 1)

# =====================================================================
# OUTPUT 3: Visualisasi Evaluasi Klaster (Elbow & Silhouette) K=2 sd 10
# =====================================================================
print("=== 3. Menyiapkan Grafik Evaluasi Klaster (K=2 hingga K=10) ===")

K_range = range(2, 11)
inertia_values = []
silhouette_scores = []

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X)
    inertia_values.append(kmeans.inertia_)
    silhouette_scores.append(silhouette_score(X, kmeans.labels_))

# Membuat Plot dengan 2 sumbu Y (kiri untuk Inertia, kanan untuk Silhouette)
fig, ax1 = plt.subplots(figsize=(10, 6))

# Plot Inertia (Elbow)
color1 = 'tab:blue'
ax1.set_xlabel('Jumlah Klaster (K)', fontsize=12, fontweight='bold')
ax1.set_ylabel('Inertia (Jarak Kuadrat Dalam Klaster)', color=color1, fontsize=12)
ax1.plot(K_range, inertia_values, marker='o', color=color1, linewidth=2, label='Inertia')
ax1.tick_params(axis='y', labelcolor=color1)

# Plot Silhouette
ax2 = ax1.twinx()
color2 = 'tab:red'
ax2.set_ylabel('Silhouette Score', color=color2, fontsize=12)
ax2.plot(K_range, silhouette_scores, marker='s', color=color2, linewidth=2, label='Silhouette Score')
ax2.tick_params(axis='y', labelcolor=color2)

# Menandai titik optimal (K = 5)
titik_k = 5
indeks_k5 = titik_k - 2 # Karena K mulai dari 2 (indeks 0)

# Garis putus-putus vertikal
ax1.axvline(x=titik_k, color='gray', linestyle='--', alpha=0.7)

# Lingkaran dan kotak tebal untuk menandai K=5
ax1.plot(titik_k, inertia_values[indeks_k5], 'o', markersize=12, markeredgecolor='black', markerfacecolor='blue')
ax2.plot(titik_k, silhouette_scores[indeks_k5], 's', markersize=12, markeredgecolor='black', markerfacecolor='red')

# Anotasi teks
ax2.annotate('Titik K Optimal (K=5)',
             xy=(titik_k, silhouette_scores[indeks_k5]),
             xytext=(titik_k+0.5, silhouette_scores[indeks_k5]+0.02),
             arrowprops=dict(facecolor='black', shrink=0.05, width=1.5, headwidth=7),
             fontsize=11, fontweight='bold')

plt.title('Evaluasi Jumlah Klaster Optimal: Elbow Method & Silhouette Score', fontsize=14, pad=15)
fig.tight_layout()
plt.grid(True, linestyle='--', alpha=0.3)
plt.show()

# =====================================================================
# OUTPUT 4: Tabel Hasil Klastering Final (34 Provinsi)
# =====================================================================
print("\n=== 4. Tabel Hasil Klastering Final (34 Provinsi) ===")

# Memastikan K-Means menggunakan K=5
kmeans_final = KMeans(n_clusters=5, random_state=42, n_init=10)
df_hasil['Label Klaster'] = kmeans_final.fit_predict(X)

# Merapikan nama kolom dan mengurutkan dari volatilitas tertinggi
df_final = df_hasil.rename(columns={
    'Provinsi': 'Nama Provinsi',
    'Nilai_Volatilitas': 'Nilai Volatilitas (σ²)'
})
df_final = df_final.sort_values(by='Nilai Volatilitas (σ²)', ascending=False).reset_index(drop=True)

# Print tabel secara utuh
pd.set_option('display.max_rows', None) # Agar semua baris tampil
print(df_final.to_string())
pd.reset_option('display.max_rows')

# =====================================================================
# OUTPUT 5: Statistik Deskriptif Klaster
# =====================================================================
print("\n=== 5. Statistik Deskriptif Per Klaster ===")

# Groupby dan Agregasi
cluster_stats = df_final.groupby('Label Klaster')['Nilai Volatilitas (σ²)'].agg(
    Count='count',
    Mean='mean',
    Min='min',
    Max='max'
).reset_index()

# Urutkan dari rata-rata volatilitas tertinggi ke terendah agar enak dibaca
cluster_stats = cluster_stats.sort_values(by='Mean', ascending=False).reset_index(drop=True)

# Rename agar tabelnya rapi
cluster_stats.rename(columns={
    'Count': 'Jumlah Provinsi',
    'Mean': 'Rata-rata Volatilitas',
    'Min': 'Volatilitas Minimum',
    'Max': 'Volatilitas Maksimum'
}, inplace=True)

print(cluster_stats.to_string(index=False))

# Opsional: Ekspor tabel untuk jurnal
# df_final.to_csv('tabel_hasil_klaster_bab4.csv', index=False)
# cluster_stats.to_csv('tabel_statistik_klaster_bab4.csv', index=False)

for i, k in enumerate(K_range):
    print(f"K={k} | Inertia={inertia_values[i]:.4f} | Silhouette={silhouette_scores[i]:.4f}")

"""#Mulai Perubahan Untuk Tuning"""

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

"""#Menghitung Volatilitas GARCH Per Provinsi"""

import pandas as pd
from arch import arch_model
import warnings

warnings.filterwarnings('ignore')

hasil_garch = []

for prov in df['provinsi'].unique():

    df_prov = df[df['provinsi'] == prov]

    volatilitas_list = []

    for komoditas in df_prov['name'].unique():

        returns = df_prov[
            df_prov['name'] == komoditas
        ]['Return_100'].dropna()

        if len(returns) < 10:
            continue

        try:

            model = arch_model(
                returns,
                mean='Constant',
                vol='GARCH',
                p=1,
                q=1
            )

            res = model.fit(disp='off')

            mean_vol = (
                res.conditional_volatility.mean()
            )

            volatilitas_list.append(mean_vol)

        except:
            continue

    if len(volatilitas_list) > 0:

        hasil_garch.append({
            'Provinsi': prov,
            'Volatilitas_GARCH': np.mean(volatilitas_list)
        })

df_garch = pd.DataFrame(hasil_garch)

print(df_garch.head())

"""# Membentuk Fitur Tambahan"""

fitur_provinsi = []

for prov in df['provinsi'].unique():

    temp = df[df['provinsi'] == prov]

    fitur_provinsi.append({

        'Provinsi': prov,

        'Mean_Return':
            temp['Return_100'].mean(),

        'Std_Return':
            temp['Return_100'].std(),

        'Max_Return':
            temp['Return_100'].max(),

        'Min_Return':
            temp['Return_100'].min()

    })

df_fitur = pd.DataFrame(fitur_provinsi)

print(df_fitur.head())

"""# Menggabungkan Semua Fitur"""

df_final_feature = pd.merge(
    df_garch,
    df_fitur,
    on='Provinsi'
)

print(df_final_feature.head())

"""# Menyimpan Dataset Fitur"""

df_final_feature.to_csv(
    'dataset_fitur_clustering.csv',
    index=False
)

print("Dataset fitur berhasil disimpan")

"""# Melihat Korelasi Antar Fitur"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

sns.heatmap(
    df_final_feature.drop(
        columns='Provinsi'
    ).corr(),
    annot=True,
    cmap='coolwarm'
)

plt.title('Korelasi Antar Fitur')

plt.show()

"""Std_Return tidak dipakai karena semakin berkorelasi tidak dipakai karena hampir membawa data yang sama

# 7 - Standardisasi

Standardisasi digunakan untuk menyamakan skala antar variabel agar tidak ada variabel yang mendominasi perhitungan jarak.
"""

# Menghapus fitur yang sangat berkorelasi

X = df_final_feature[
    [
        'Volatilitas_GARCH',
        'Mean_Return',
        'Max_Return',
        'Min_Return'
    ]
]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print("Shape X :", X.shape)
print("Shape X_scaled :", X_scaled.shape)

"""# 8 - PCA

PCA digunakan untuk mengurangi jumlah variabel dengan tetap mempertahankan sebagian besar informasi yang terkandung dalam data.
Misal ada variabel FISIKA, KIMIA, MATEMATIKA. dengan PCA menjadi Sains
"""

from sklearn.decomposition import PCA

pca = PCA()

X_pca = pca.fit_transform(X_scaled)

print("Explained Variance Ratio")
print(pca.explained_variance_ratio_)

print("\nCumulative Variance")
print(
    np.cumsum(
        pca.explained_variance_ratio_
    )
)

"""Principal Component Analysis  
Mengurangi jumlah variabel
tanpa kehilangan terlalu banyak informasi.

# 9 - Menentukan jumlah komponen PCA
"""

plt.figure(figsize=(8,5))

plt.plot(
    range(
        1,
        len(pca.explained_variance_ratio_)+1
    ),
    np.cumsum(
        pca.explained_variance_ratio_
    ),
    marker='o'
)

plt.axhline(
    y=0.95,
    linestyle='--'
)

plt.xlabel('Jumlah Komponen')

plt.ylabel('Cumulative Variance')

plt.title(
    'Pemilihan Komponen PCA'
)

plt.grid(True)

plt.show()

"""# 10"""

pca_final = PCA(
    n_components=0.95
)

X_pca = pca_final.fit_transform(
    X_scaled
)

print(
    "Shape PCA Final:",
    X_pca.shape
)

print(
    "Variance Retained:",
    pca_final.explained_variance_ratio_.sum()
)

"""# 11 - Evaluasi seluruh K."""

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

K_range = range(2,11)

scores = []

for k in K_range:

    model = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=500
    )

    labels = model.fit_predict(
        X_pca
    )

    score = silhouette_score(
        X_pca,
        labels
    )

    scores.append(score)

    print(
        f"K={k} | Silhouette={score:.4f}"
    )

"""# 12 - Grafik evaluasi."""

plt.figure(figsize=(8,5))

plt.plot(
    list(K_range),
    scores,
    marker='o'
)

plt.xlabel('Jumlah Cluster')

plt.ylabel('Silhouette Score')

plt.title(
    'Evaluasi Silhouette Score'
)

plt.grid(True)

plt.show()

"""# 13 - Tuning khusus K = 5."""

best_score = -1
best_state = None

for rs in range(100):

    model = KMeans(
        n_clusters=5,
        random_state=rs,
        n_init=100
    )

    labels = model.fit_predict(
        X_pca
    )

    score = silhouette_score(
        X_pca,
        labels
    )

    if score > best_score:

        best_score = score
        best_state = rs

print(
    f"Best Random State = {best_state}"
)

print(
    f"Best Silhouette = {best_score:.4f}"
)

"""# 14 - Clustering Final"""

kmeans_final = KMeans(
    n_clusters=5,
    random_state=best_state,
    n_init=500
)

cluster = kmeans_final.fit_predict(
    X_pca
)

df_final_feature['Cluster'] = cluster

print(
    df_final_feature
    .sort_values(
        'Volatilitas_GARCH',
        ascending=False
    )
)

"""# 15 - Profil Cluster"""

cluster_profile = (
    df_final_feature
    .groupby('Cluster')
    [
        [
            'Volatilitas_GARCH',
            'Mean_Return',
            'Max_Return',
            'Min_Return'
        ]
    ]
    .mean()
)

print(cluster_profile)

"""# 16 - Kontribusi Masing-masing Fitur Terhadap PCA"""

loading = pd.DataFrame(
    pca_final.components_.T,
    columns=[
        f'PC{i+1}'
        for i in range(
            pca_final.n_components_
        )
    ],
    index=X.columns
)

print(loading)

"""# Agglomerative"""

from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import silhouette_score

X = df_hasil[['Nilai_Volatilitas']]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

agg = AgglomerativeClustering(
    n_clusters=5,
    linkage='ward'
)

labels = agg.fit_predict(X_scaled)

score = silhouette_score(
    X_scaled,
    labels
)

print(score)

"""# Gaussian Mixture"""

from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score

X = df_hasil[['Nilai_Volatilitas']]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

gmm = GaussianMixture(
    n_components=5,
    random_state=42
)

labels = gmm.fit_predict(X_scaled)

score = silhouette_score(
    X_scaled,
    labels
)

print(score)

"""# K terbaik"""

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

X = df_hasil[['Nilai_Volatilitas']]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

for k in range(2,11):

    model = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=100
    )

    labels = model.fit_predict(X_scaled)

    score = silhouette_score(
        X_scaled,
        labels
    )

    print(f"K={k} | {score:.4f}")

"""# Validasi Elbow Method"""

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

X = df_hasil[['Nilai_Volatilitas']]

inertia = []

for k in range(1,11):

    model = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=100
    )

    model.fit(X)

    inertia.append(model.inertia_)

plt.figure(figsize=(8,5))

plt.plot(
    range(1,11),
    inertia,
    marker='o'
)

plt.xlabel('Jumlah Cluster')
plt.ylabel('WCSS')
plt.title('Elbow Method')

plt.show()

"""# Hitung Davies-Bouldin Index"""

from sklearn.metrics import davies_bouldin_score

kmeans = KMeans(
    n_clusters=5,
    random_state=42,
    n_init=100
)

labels = kmeans.fit_predict(X)

dbi = davies_bouldin_score(
    X,
    labels
)

print("Davies Bouldin Index :", dbi)

"""# Profil Cluster"""

profil = (
    df_hasil
    .groupby('Cluster')
    ['Nilai_Volatilitas']
    .agg(
        [
            'count',
            'mean',
            'min',
            'max',
            'std'
        ]
    )
)

print(profil)

"""# Analisis Provinsi

Provinsi paling volatil dan
Provinsi paling stabil
"""

df_hasil.sort_values(
    'Nilai_Volatilitas',
    ascending=False
)

"""# Grid Search"""

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import pandas as pd

results = []

for k in range(2,11):

    for init in ['k-means++', 'random']:

        for n_init in [10, 50, 100]:

            model = KMeans(
                n_clusters=5,
                init=init,
                n_init=n_init,
                random_state=42
            )

            labels = model.fit_predict(X)

            score = silhouette_score(
                X,
                labels
            )

            results.append({
                'K': 5,
                'Init': init,
                'N_Init': n_init,
                'Silhouette': score
            })

hasil = pd.DataFrame(results)

hasil.sort_values(
    'Silhouette',
    ascending=False
).head(10)

"""# Random Search"""

import random
import pandas as pd

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

results = []

for i in range(200):

    k = random.randint(2, 10)

    init = random.choice([
        'k-means++',
        'random'
    ])

    n_init = random.randint(
        10,
        200
    )

    max_iter = random.randint(
        100,
        1000
    )

    model = KMeans(
        n_clusters=k,
        init=init,
        n_init=n_init,
        max_iter=max_iter,
        random_state=42
    )

    labels = model.fit_predict(X)

    score = silhouette_score(
        X,
        labels
    )

    results.append({
        'K': k,
        'Init': init,
        'N_Init': n_init,
        'Max_Iter': max_iter,
        'Silhouette': score
    })

hasil_random = pd.DataFrame(results)

df_final.info()

print(df_final.head())

print(df_final.columns)

mapping = {
    4: 'Sangat Rendah',
    1: 'Rendah',
    3: 'Sedang',
    0: 'Tinggi',
    2: 'Sangat Tinggi'
}

df_final['Kategori Volatilitas'] = (
    df_final['Label Klaster']
    .map(mapping)
)

print('Kategori Volatilitas')

df_final.to_csv(
    'hasil_clustering_cabai.csv',
    index=False
)

"""Penelitian diawali dengan melakukan pemodelan volatilitas menggunakan GARCH(1,1) pada data harga cabai rawit merah setiap provinsi. Nilai volatilitas yang diperoleh kemudian digunakan sebagai satu-satunya fitur dalam proses clustering menggunakan K-Means.

Model awal menghasilkan Silhouette Score sebesar 0,6498 pada K=5, yang menunjukkan kualitas cluster yang baik.

Untuk meningkatkan performa model, dilakukan beberapa eksperimen, antara lain:

Menambahkan fitur statistik return (Mean Return, Std Return, Max Return, dan Min Return).
Melakukan standardisasi data.
Menerapkan PCA (Principal Component Analysis).
Mencoba transformasi data (Log Transformation dan Quantile Transformation).
Membuat fitur tambahan dari output GARCH (MeanVol, StdVol, dan MaxVol).
Membandingkan algoritma K-Means, Agglomerative Clustering, dan Gaussian Mixture Model.
Melakukan pencarian parameter menggunakan tuning dan evaluasi berbagai jumlah cluster.

Hasil pengujian menunjukkan bahwa seluruh metode tambahan tersebut tidak mampu menghasilkan performa yang lebih baik dibandingkan model awal. Bahkan beberapa eksperimen menyebabkan penurunan nilai Silhouette Score secara signifikan.

Evaluasi akhir menghasilkan:

Silhouette Score = 0,6498
Davies-Bouldin Index = 0,427

Berdasarkan hasil tersebut, model terbaik tetap menggunakan satu fitur Volatilitas GARCH dengan algoritma K-Means dan jumlah cluster sebanyak 5, karena memberikan keseimbangan terbaik antara kualitas cluster dan kemudahan interpretasi hasil penelitian.
"""